services:
  database:
    platform: linux/amd64
    image: library/mysql:9.1.0
    container_name: lifelog_db

    environment:
      MYSQL_USER: myuser
      MYSQL_DATABASE: mydb
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - "/home/chan/life-log/database/:/var/lib/mysql"
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://lifelog_db:3306/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword